import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dm = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${dm.className} overflow-x-hidden overflow-y-hidden w-full h-full bg-cover bg-[url('/stars.jpeg')] text-white`}>
        <div className="overflow-x-auto w-full h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
